# Check on http://lint.travis-ci.org/ after modifying it!
# sudo: required
language: c
os:
  - linux
  - osx
env:
  matrix:
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    - secure: "e/VyjGTs9HZGnu+q9ysnOsoUWdokawJGVoiFzFNJCxMgRguihAiJBEpEd1bcitI+y9/RRh+LU8LJWVVSDnQgZ3Z5Xd++xKS0z4O9Jo8zw3t8jcGQvS3BjIufyIirEJvhmz0l9ywPzBTxNMCi3N6PIDl6TZhu3UmURXOWdGFutUCcVPcJisTiNG2Pq2LIUxUSk66MqZGWGkrCpzZ0UXmzMwWx+AhR14uuROBhB8WFkIaUEVDmBmMwDnGZBRXO/joTKrHXNPo+jjXG81VuXn/joN7dWz07ghDNBlaKl/zLPhElcqOY7F/VklpUZRbxvHY/8N3k/BGQ+wFq19jEBVqWJbNFu8ObEW8gW2gcCdzQW8qJzMG2iFiFlXLchpz47WNDmDY77/kMor9Rv8amk3tR2GUOrixE+THfptFsj5hHn33wRp/Ve5gdOAplg66yaWLRdjpF6E0QPZ3Yb6Msdp6olgC37P2KlqhZQJ0Gy9xEfqScLYEDZlh0DBVpr/mpm85dNNeGwnvbUdGTP9Oev8+RN9v4CkfU8RcYfe+aw/hcPAzXW6fMiCZSql8E+21PBhKxsfGMuObxCiA5nHhGZITTEZ/rFseboPgiMe+Py5c9IsUNnjRFT/nVqiOQ4eFi1qvBgOXVMXrHtN0UwAz+wpbURqCk8WV/Huf78weXnijSqyk="

before_install:
  - echo "$TRAVIS_OS_NAME"
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh; fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels https://conda.anaconda.org/biocore
  - conda config --add channels conda-forge
  - conda config --add channels bioconda
  # Update conda itself
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  # xvfb is required to test plot and gui for linux
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y xvfb; fi
install:
  - conda install --yes --file ci/conda_requirements.txt
  - pip install -r ci/pip_requirements.txt
  - pip install . --no-deps
before_script:
  - export DISPLAY=:99.0
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi
script:
  - WITH_COVERAGE=TRUE make all
notifications:
  webhooks:
    on_success: change
    on_failure: always
after_success:
  - coveralls
  - source publish.sh
