package:
  name: calour
  version: "0.99_beta"

source:
  git_url: git@github.com:biocore/calour.git
  git_rev: 0.99-beta

requirements:
  build:
    - python
    - nose
    - setuptools
    - numpy
    - scipy
    - pandas
    - matplotlib >=2.0
    - scikit-learn
    - scikit-bio
    - biom-format
    - statsmodels
    - ipython
    - ipywidgets
    - pyqt >5
  run:
    - python
    - nose
    - setuptools
    - numpy
    - scipy
    - pandas
    - matplotlib >=2.0
    - scikit-learn
    - scikit-bio
    - biom-format
    - statsmodels
    - ipython
    - ipywidgets
    - pyqt >5

test:
  # Python imports
  imports:
    - calour
    - calour.experiment

about:
  home: https://github.com/biocore/calour
  license: Modified BSD License
  summary: exploratory and interactive microbiome analyses based on heatmaps

